use swiggy;
select * from swiggy;

SELECT *,RANK() OVER(ORDER BY cost DESC) FROM swiggy;
SELECT *,DENSE_RANK() OVER(ORDER BY cost DESC) FROM swiggy;
SELECT *,ROW_NUMBER() OVER(ORDER BY cost DESC) FROM swiggy;








SELECT *,RANK() OVER(ORDER BY cost DESC) FROM restaurants;
SELECT *,DENSE_RANK() OVER(ORDER BY cost DESC) FROM restaurants;
SELECT *,ROW_NUMBER() OVER(ORDER BY cost ASC) FROM restaurants;






-- 1. Rank every restaurant from most expensive to least expensive

SELECT *,ROW_NUMBER() OVER(order by cost DESC) FROM swiggy;



select *, rank() over(order by cost desc) as 'rank' from restaurants;


-- 2. Rank every restaurant from most visited to least visited

SELECT *,DENSE_RANK() OVER(order by rating_count DESC) FROM swiggy;



SELECT *,ROW_NUMBER() OVER(order by rating_count DESC) as 'rank' FROM restaurants;



select *, rank() over(order by rating_count desc) as 'rank' from restaurants;


-- 3. Rank every restaurant from most expensive to least expensive as per their city

SELECT *,ROW_NUMBER() OVER(PARTITION BY city ORDER BY cost DESC) FROM swiggy;


-- RANK every restaurant from most to least expensive as per the cuisine.

SELECT *,RANK() OVER(PARTITION BY cuisine ORDER BY cost DESC) FROM swiggy;


SELECT *,ROW_number() OVER(PARTITION BY city ORDER BY cost DESC) FROM restaurants;


select *, rank() over(partition by city order by cost desc) as 'rank' from restaurants;
select *, dense_rank() over(partition by city order by cost desc) as 'rank' from restaurants;
select *, row_number() over() as 'rank' from restaurants;


-- 4. Dense-rank every restaurant from most expensive to least expensive as per their city

SELECT *,DENSE_RANK() OVER(PARTITION BY city ORDER BY cost DESC) FROM swiggy;


select *, 
	rank() over(partition by city order by cost desc) as 'rank' ,
	dense_rank() over(partition by city order by cost desc) as 'dense_rank',
    row_number() over(partition by city order by cost desc) as 'row_number'
from restaurants;

-- -Rank the restaurant based on their prices (most to least exp) as per the cuisine(row_number,dense_rank,rank)
SELECT *, 
		rank() over(partition by cuisine order by cost desc) as 'rank',
		dense_rank() over(partition by cuisine order by cost desc) as 'rank',
		row_number() over(partition by cuisine order by cost desc) as 'rank'
FROM restaurants;



-- 5. Row-number every restaurant from most expensive to least expensive as per their city
select *, row_number() over(partition by city order by cost desc) as 'rank' from restaurants;



-- 6. Rank every restaurant from most expensive to least expensive as per their city along with its city [Adilabad - 1, Adilabad - 2]


select *, concat(city ,'-',row_number() over(partition by city order by cost desc)) as 'rank' from swiggy;




-- 7. Find top 5 restaurants of every city as per their revenue


SELECT * FROM (
SELECT *,ROW_NUMBER() OVER(PARTITION BY city ORDER BY cost*rating_count DESC) as 'rank'
FROM swiggy
) as t
WHERE t.rank <= 5;


-- Find Top 2 Costliest Restaurants per City

SELECT * FROM
(SELECT *,ROW_NUMBER() OVER(PARTITION BY City ORDER BY cost DESC) as 'rank' FROM swiggy) as t
WHERE t.rank <= 2;









SELECT *
FROM (
    SELECT
        name,
        city,
        cost,
        row_number() OVER (PARTITION BY city ORDER BY cost DESC) AS cost_rank
    FROM restaurants
) t
WHERE cost_rank <= 2;


select city,sum(revenue) as 'revenue' from (
	select *, 
		cost*rating_count as 'revenue',
		rank() over(partition by city order by rating_count*cost desc) as 'rank' 
	from restaurants
) t where t.rank <= 5
	group by city
		order by revenue desc limit 5;



select cuisine,sum(revenue) as 'revenue' from (
	select *, 
		cost*rating_count as 'revenue',
		row_number() over(partition by cuisine order by rating_count*cost desc) as 'rank' 
	from restaurants
) t where t.rank <= 5
	group by cuisine
		order by revenue desc limit 5;


-- 8. Find top 5 restaurants of every cuisine as per their revenue

SELECT * FROM
(SELECT *,ROW_NUMBER() OVER(PARTITION BY cuisine ORDER BY cost*rating_count DESC) as 'rank'FROM swiggy) t
WHERE t.rank <= 5;




select * from (
	select *, 
		cost*rating_count as 'revenue',
		row_number() over(partition by cuisine order by rating_count*cost desc) as 'rank' 
	from restaurants
) t where t.rank <= 5;

-- 9. List the top 5 cuisines as per the revenue generated by top 5 restaurants of every cuisine

SELECT cuisine, SUM(cost*rating_count) FROM
(SELECT *,ROW_NUMBER() OVER(PARTITION BY cuisine ORDER BY cost*rating_count DESC) as 'rank' FROM swiggy) as t
WHERE t.rank <= 5
GROUP BY cuisine
ORDER BY SUM(cost*rating_count) DESC LIMIT 5;

-- List the top 5 city as per the revenue generated by the top 5 restaurant of every city

SELECT city, SUM(cost*rating_count) FROM 
(SELECT *,ROW_NUMBER() OVER(PARTITION BY city ORDER BY cost*rating_count DESC) as 'rank' FROM swiggy) t
WHERE t.rank <= 5
GROUP BY city
ORDER BY SUM(cost*rating_count) DESC LIMIT 5;












select cuisine, sum(rating_count * cost) as 'revenue' from (
	select *, 
		cost*rating_count as 'revenue',
		row_number() over(partition by cuisine order by rating_count*cost desc) as 'rank' 
	from restaurants
) t 
where t.rank <= 5
group by cuisine
order by revenue desc 
limit 5;

        