use restaurants;
select * from swiggy;
SELECT * FROM restaurants;

SELECT *,RANK() OVER(order by cost DESC) FROM restaurants;
SELECT *,DENSE_RANK() OVER(order by cost DESC) FROM restaurants;
SELECT *,ROW_NUMBER() OVER(order by cost DESC) FROM restaurants;




-- 1. Rank every restaurant from most expensive to least expensive




SELECT *, RANK() OVER(ORDER BY COST DESC)  FROM SWIGGY;
SELECT *, DENSE_RANK() OVER(ORDER BY COST DESC) FROM SWIGGY;
SELECT *, ROW_NUMBER() OVER(ORDER BY COST DESC) FROM SWIGGY;


select *, rank() over(order by cost desc) as 'rank' from swiggy;


-- 2. Rank every restaurant from most visited to least visited

SELECT *,RANK() OVER(ORDER BY rating_count DESC) FROM restaurants;


SELECT *, ROW_NUMBER() OVER(ORDER BY RATING_COUNT DESC) FROM SWIGGY;

select *, rank() over(order by rating_count desc) as 'rank' from swiggy;


-- 3. Rank every restaurant from most expensive to least expensive as per their city





SELECT *,RANK() OVER(PARTITION BY city ORDER BY COST DESC) FROM restaurants;




select *, rank() over(partition by city order by cost desc) as 'rank' from swiggy;
select *, dense_rank() over(partition by city order by cost desc) as 'rank' from swiggy;
select *, row_number() over() as 'rank' from swiggy;


-- 4. Dense-rank every restaurant from most expensive to least expensive as per their city


select *, 
	rank() over(partition by city order by cost desc) as 'rank' ,
	dense_rank() over(partition by city order by cost desc) as 'dense_rank',
    row_number() over(partition by city order by cost desc) as 'row_number'
from swiggy;

-- Rank the restaurant based on their prices (most to least exp) 
-- as per the cuisine(row_number,dense_rank,rank)

SELECT *,
RANK() OVER(partition by cuisine ORDER BY cost DESC),
DENSE_RANK() OVER(partition by cuisine ORDER BY cost DESC)
FROM restaurants;



SELECT *, 
		rank() over(partition by cuisine order by cost desc) as 'rank',
		dense_rank() over(partition by cuisine order by cost desc) as 'rank',
		row_number() over(partition by cuisine order by cost desc) as 'rank'
FROM swiggy;



-- 5. Row-number every restaurant from most expensive to least expensive as per their city




select *, row_number() over(partition by city order by cost desc) as 'rank' from swiggy;



-- 6. Rank every restaurant from most expensive to least expensive as per 
-- their city along with its city [Adilabad - 1, Adilabad - 2]




select *, concat(city ,'-',row_number() over(partition by city order by cost desc)) as 'rank' from restaurants;



-- 7. Find top 5 restaurants of every city as per their revenue


SELECT * FROM(
SELECT *, rating_count*cost,ROW_NUMBER() OVER(PARTITION BY CITY ORDER BY rating_count*cost DESC) as 'RANKS'
FROM restaurants
) t WHERE t.RANKS < 6;








SELECT * FROM (
SELECT *, ROW_NUMBER() OVER(PARTITION BY CITY ORDER BY COST*RATING_COUNT DESC) AS 'RANKING' FROM SWIGGY
) AS T
WHERE T.RANKING <= 5;


select * from (
	select *, 
		cost*rating_count as 'revenue',
		row_number() over(partition by city order by rating_count*cost desc) as 'rank' 
	from swiggy
) t where t.rank <= 5;



select city,sum(revenue) as 'revenue' from (
	select *, 
		cost*rating_count as 'revenue',
		rank() over(partition by city order by rating_count*cost desc) as 'rank' 
	from swiggy
) t where t.rank <= 5
	group by city
		order by revenue desc limit 5;


select cuisine,sum(revenue) as 'revenue' from (
	select *, 
		cost*rating_count as 'revenue',
		row_number() over(partition by cuisine order by rating_count*cost desc) as 'rank' 
	from swiggy
) t where t.rank <= 5
	group by cuisine
		order by revenue desc limit 5;


-- 8. Find top 5 restaurants of every cuisine as per their revenue

SELECT * FROM(
SELECT *,ROW_NUMBER() OVER(partition by cuisine ORDER BY rating_count*cost DESC) as "ROWS"
FROM restaurants
) t 
WHERE t.ROWS < 6;






select * from (
	select *, 
		cost*rating_count as 'revenue',
		row_number() over(partition by cuisine order by rating_count*cost desc) as 'rank' 
	from swiggy
) t where t.rank <= 5;




-- 9. List the top 5 cuisines as per the revenue generated by top 5 restaurants of every cuisine

SELECT cuisine, SUM(cost*rating_count) FROM
(
SELECT *,row_number() OVER(partition by cuisine ORDER BY cost*rating_count DESC) as 'ROWS'
FROM restaurants) t
WHERE t.ROWS <6
GROUP BY cuisine
ORDER BY SUM(cost*rating_count) DESC LIMIT 5;






select cuisine, sum(rating_count * cost) as 'revenue' from (
	select *, 
		cost*rating_count as 'revenue',
		row_number() over(partition by cuisine order by rating_count*cost desc) as 'rank' 
	from restaurants
) t 
where t.rank <= 5
group by cuisine
order by revenue desc 
limit 5;


-- List the top 5 restaurants as per their revenue generated by the top 5 restaurants of every city

SELECT city, SUM(cost*rating_count) FROM(
SELECT *,row_number() OVER(partition by city order by cost*rating_count DESC) as 'ROWS'
FROM restaurants
) t 
WHERE t.ROWS < 6
GROUP BY city 
ORDER BY SUM(cost*rating_count) DESC LIMIT 5;








-- 10. What is the total revenue generated by top 1% restaurants

SELECT SUM(rating_count*cost) FROM(
SELECT *,row_number() OVER(order by rating_count*cost DESC) as "ROWS"
FROM restaurants) t
WHERE t.ROWS < (SELECT COUNT(*)/100 FROM restaurants);


--  462,914,000 = 17.5%
-- 11. Check the same for top 20% restaurants

SELECT SUM(rating_count*cost) FROM(
SELECT *,row_number() OVER(order by rating_count*cost DESC) as "ROWS"
FROM restaurants) t
WHERE t.ROWS < (SELECT (COUNT(*)/100)*20 FROM restaurants);


select sum(cost*rating_count) as 'total_revenue'
from (select *, cost*rating_count ,row_number() over(order by cost*rating_count desc) as 'rank' from swiggy) t
where t.rank <= (((select count(*) from swiggy)/100)*20);

-- 12. What % of revenue is generated by top 20% of restaurants with respect to total revenue?


SELECT SUM(cost*rating_count) FROM restaurants;




with
	q1 as ( select sum(cost*rating_count) as 'top_revenue'
			from (select *, cost*rating_count ,row_number() over(order by cost*rating_count desc) as 'rank' from restaurants) t
			where t.rank <= (((select count(*) from restaurants)/100)*20)),
            
	q2 as ( select sum(rating_count*cost) as 'total_revenue' from restaurants)
    
SELECT round((top_revenue/total_revenue)*100) as 'revenue %' FROM q1, q2;







select sum(cost*rating_count) as 'total_revenue'
	from (
			select *, cost*rating_count ,
            row_number() over(partition by city order by cost*rating_count desc) as 'rank'
			from swiggy) t
where t.rank <= ((select count(*) from swiggy)/100);



select city,sum(revenue) as 'total_revenue' from 
	(
		select *,  cost*rating_count as 'revenue',
			row_number() over(partition by city order by rating_count*cost desc) as 'rank' 
				from restaurants
	) as t1
		where t1.rank <= 5
        group by city
        order by total_revenue desc limit 5;