use restaurants;
select * from swiggy;





-- 1. Rank every restaurant from most expensive to least expensive

SELECT *, RANK() OVER(ORDER BY COST DESC)  FROM SWIGGY;
SELECT *, DENSE_RANK() OVER(ORDER BY COST DESC) FROM SWIGGY;
SELECT *, ROW_NUMBER() OVER(ORDER BY COST DESC) FROM SWIGGY;


select *, rank() over(order by cost desc) as 'rank' from swiggy;


-- 2. Rank every restaurant from most visited to least visited


SELECT *, ROW_NUMBER() OVER(ORDER BY RATING_COUNT DESC) FROM SWIGGY;

select *, rank() over(order by rating_count desc) as 'rank' from swiggy;


-- 3. Rank every restaurant from most expensive to least expensive as per their city

SELECT CITY,SUM(COST) FROM (
(SELECT *,ROW_NUMBER() OVER(PARTITION BY CITY ORDER BY COST DESC) AS 'RANK' FROM SWIGGY)
) AS T
WHERE T.RANK <= 5
GROUP BY CITY
ORDER BY SUM(COST) DESC;



select *, rank() over(partition by city order by cost desc) as 'rank' from swiggy;
select *, dense_rank() over(partition by city order by cost desc) as 'rank' from swiggy;
select *, row_number() over() as 'rank' from swiggy;


-- 4. Dense-rank every restaurant from most expensive to least expensive as per their city

select *, 
	rank() over(partition by city order by cost desc) as 'rank' ,
	dense_rank() over(partition by city order by cost desc) as 'dense_rank',
    row_number() over(partition by city order by cost desc) as 'row_number'
from swiggy;

-- -Rank the restaurant based on their prices (most to least exp) as per the cuisine(row_number,dense_rank,rank)

SELECT *, 
		rank() over(partition by cuisine order by cost desc) as 'rank',
		dense_rank() over(partition by cuisine order by cost desc) as 'rank',
		row_number() over(partition by cuisine order by cost desc) as 'rank'
FROM swiggy;



-- 5. Row-number every restaurant from most expensive to least expensive as per their city


select *, row_number() over(partition by city order by cost desc) as 'rank' from swiggy;



-- 6. Rank every restaurant from most expensive to least expensive as per their city along with its city [Adilabad - 1, Adilabad - 2]


select *, concat(city ,'-',row_number() over(partition by city order by cost desc)) as 'rank' from swiggy;



-- 7. Find top 5 restaurants of every city as per their revenue

SELECT * FROM (
SELECT *, ROW_NUMBER() OVER(PARTITION BY CITY ORDER BY COST*RATING_COUNT DESC) AS 'RANKING' FROM SWIGGY
) AS T
WHERE T.RANKING <= 5;


select * from (
	select *, 
		cost*rating_count as 'revenue',
		row_number() over(partition by city order by rating_count*cost desc) as 'rank' 
	from swiggy
) t where t.rank <= 5;



select city,sum(revenue) as 'revenue' from (
	select *, 
		cost*rating_count as 'revenue',
		rank() over(partition by city order by rating_count*cost desc) as 'rank' 
	from swiggy
) t where t.rank <= 5
	group by city
		order by revenue desc limit 5;


select cuisine,sum(revenue) as 'revenue' from (
	select *, 
		cost*rating_count as 'revenue',
		row_number() over(partition by cuisine order by rating_count*cost desc) as 'rank' 
	from swiggy
) t where t.rank <= 5
	group by cuisine
		order by revenue desc limit 5;


-- 8. Find top 5 restaurants of every cuisine as per their revenue

select * from (
	select *, 
		cost*rating_count as 'revenue',
		row_number() over(partition by cuisine order by rating_count*cost desc) as 'rank' 
	from swiggy
) t where t.rank <= 5;

-- 9. List the top 5 cuisines as per the revenue generated by top 5 restaurants of every cuisine


select cuisine, sum(rating_count * cost) as 'revenue' from (
	select *, 
		cost*rating_count as 'revenue',
		row_number() over(partition by cuisine order by rating_count*cost desc) as 'rank' 
	from swiggy
) t 
where t.rank <= 5
group by cuisine
order by revenue desc 
limit 5;


-- 10. What % of the total revenue is generated by top 1% restaurants




select sum(cost*rating_count) as 'total_revenue'
	from (
			select *, cost*rating_count ,row_number() over(order by cost*rating_count desc) as 'rank' 
			from swiggy) t
where t.rank <= ((select count(*) from swiggy)/100);

--  462,914,000 = 17.5%

-- 11. Check the same for top 20% restaurants


select sum(cost*rating_count) as 'total_revenue'
from (select *, cost*rating_count ,row_number() over(order by cost*rating_count desc) as 'rank' from swiggy) t
where t.rank <= (((select count(*) from swiggy)/100)*20);

-- 12. What % of revenue is generated by top 20% of restaurants with respect to total revenue?
with
	q1 as ( select sum(cost*rating_count) as 'top_revenue'
			from (select *, cost*rating_count ,row_number() over(order by cost*rating_count desc) as 'rank' from swiggy) t
			where t.rank <= (((select count(*) from swiggy)/100)*20)),
            
	q2 as ( select sum(rating_count*cost) as 'total_revenue' from swiggy)
    
SELECT round((top_revenue/total_revenue)*100) as 'revenue %' FROM q1, q2;







select sum(cost*rating_count) as 'total_revenue'
	from (
			select *, cost*rating_count ,
            row_number() over(partition by city order by cost*rating_count desc) as 'rank'
			from swiggy) t
where t.rank <= ((select count(*) from swiggy)/100);



select city,sum(revenue) as 'total_revenue' from 
	(
		select *,  cost*rating_count as 'revenue',
			row_number() over(partition by city order by rating_count*cost desc) as 'rank' 
				from restaurants
	) as t1
		where t1.rank <= 5
        group by city
        order by total_revenue desc limit 5;